FROM node:15.5-alpine as BUILD

WORKDIR /usr/src/app
COPY package*.json yarn.lock ./
RUN yarn cache clean && yarn --update-checksums
COPY . .
RUN yarn && yarn build

# Stage - production
FROM nginx:1.17-alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]