name: merge

on:
  pull_request:
    branches:
      - master

jobs:
  check_merge:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.0'
      - name: Install yarn and run tests
        run: |
          yarn
          yarn test
        env:
          CI: true
